# Copyright (C) 2013-2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/m7vzw/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/htc/m7vzw/proprietary/etc/firmware/BCM4335B0_002.001.006.0296.0299.hcd:system/etc/firmware/BCM4335B0_002.001.006.0296.0299.hcd
PRODUCT_COPY_FILES += \
    vendor/htc/m7vzw/proprietary/bin/efsks:system/bin/efsks \
    vendor/htc/m7vzw/proprietary/bin/netmgrd:system/vendor/bin/netmgrd \
    vendor/htc/m7vzw/proprietary/bin/qcks:system/bin/qcks \
    vendor/htc/m7vzw/proprietary/bin/qmuxd:system/vendor/bin/qmuxd \
    vendor/htc/m7vzw/proprietary/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/htc/m7vzw/proprietary/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/htc/m7vzw/proprietary/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/htc/m7vzw/proprietary/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/htc/m7vzw/proprietary/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/htc/m7vzw/proprietary/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/htc/m7vzw/proprietary/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/htc/m7vzw/proprietary/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/htc/m7vzw/proprietary/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/htc/m7vzw/proprietary/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/htc/m7vzw/proprietary/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/htc/m7vzw/proprietary/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/htc/m7vzw/proprietary/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/htc/m7vzw/proprietary/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/htc/m7vzw/proprietary/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/htc/m7vzw/proprietary/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/htc/m7vzw/proprietary/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so
